site_name: OpenStreetMap API doc
theme: 
  name: material
  language: en
  favicon: assets/faviconJS.ico
  font:
    text: Roboto
    code: Lekton
  theme:
  features:
    - content.code.copy
  icon:
    logo: fontawesome/solid/map
    annotation: material/plus-circle
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: pink
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: pink
      accent: green
  plugins:
  - social
nav:
  - Welcome to OSM API doc: index.md
  - When NOT to use the API: when_NOT_to_use_the_API.md
  - Overview: overview.md
  - General informations:
    - Info: general_informations/info.md
    - URL + authentification: general_informations/URL_+_authentication.md
    - Elements: general_informations/elements.md
    - Changesets: general_informations/changesets.md
    - Tags: general_informations/tags.md
    - Maximum string lenghts: general_informations/maximum_string_lenghts.md
    - Reliably identifying users: general_informations/reliably_identifying_users.md
    - Version num and opti lock: general_informations/version_numbers_and_optimistic_locking.md
    - Internal errors with response: general_informations/internal_errors_while_generating_a_response.md
  - Endpoints (API calls):
    - Miscellaneous:
      - Get API versions: endpoints_(API_calls)/get_api_versions.md
      - Get API capabilities: endpoints_(API_calls)/get_api_capabilities.md
      - Get API map: endpoints_(API_calls)/get_api_map.md
      - Get API permissions: endpoints_(API_calls)/get_api_permissions.md
    - Elements:
      - Nodes:
        - Create node: endpoints_(API_calls)/create_node.md
        - Get node: endpoints_(API_calls)/get_node.md
        - Update node: endpoints_(API_calls)/update_node.md
        - Delete node: endpoints_(API_calls)/delete_node.md
      - Ways:
        - Create way: endpoints_(API_calls)/create_way.md
        - Get way: endpoints_(API_calls)/get_way.md
        - Update way: endpoints_(API_calls)/update_way.md
        - Delete way: endpoints_(API_calls)/delete_way.md
      - Relations:
        - Create relation: endpoints_(API_calls)/create_relation.md
        - Get relation: endpoints_(API_calls)/get_relation.md
        - Update relation: endpoints_(API_calls)/update_relation.md
        - Delete relation: endpoints_(API_calls)/delete_relation.md
    - Changesets:
      - Get changesets: endpoints_(API_calls)/get_changesets.md
    - Notes:
      - Create note: endpoints_(API_calls)/create_note.md
      - Get notes by bbox: endpoints_(API_calls)/get_notes_by_bbox.md
    - Methods for user data:
      - Get user details: endpoints_(API_calls)/get_user_details.md
  - Semantic versioning: semantic_versioning.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/j%C4%99drzej-j-steckiewicz-395659334/

copyright: Copyright &copy; 2025 Jędrzej Steckiewicz