site_name: OpenStreetMap API doc
theme: 
  name: material
  language: en
  font:
    text: Roboto
    code: Lekton
  icon:
    logo: fontawesome/solid/map
    annotation: material/plus-circle
  favicon: assets/faviconJS.ico
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: pink
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: pink
      accent: green
  plugins:
  - social
nav:
  - Welcome to OSM API doc: index.md
  - When NOT to use the API: when_NOT_to_use_the_API.md
  - Overview: Overview.md
  - General informations:
    - Info: general_informations/info.md
    - URL + authentification: general_informations/URL_+_authentication.md
    - Elements: general_informations/elements.md
    - Changesets: general_informations/changesets.md
    - Tags: general_informations/tags.md
    - Maximum string lenghts: general_informations/maximum_string_lenghts.md
    - Reliably identifying users: general_informations/reliably_identifying_users.md
    - Version num and opti lock: general_informations/version_numbers_and_optimistic_locking.md
    - Faking the correct HTTP: general_informations/faking_the_correct_HTTP_methods.md
    - Internal errors with response: general_informations/internal_errors_while_generating_a_response.md
  - Endpoints (API calls):
    - Miscellaneous: endpoints_(API_calls)/miscellaneous.md
  - Semantic versioning: semantic_versioning.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/j%C4%99drzej-j-steckiewicz-395659334/

copyright: Copyright &copy; 2025 Jędrzej Steckiewicz