site_name: OpenStreetMap API doc
theme: 
  name: material
  language: en
  font:
    text: Roboto
    code: Lekton
  icon:
    logo: fontawesome/solid/map
    annotation: material/plus-circle
  favicon: assets/faviconJS.ico
  palette:
    primary: green
    accent: pink
  plugins:
  - social
nav:
  - Welcome to OSM API doc: index.md
  - Overview: Overview.md
  - General informations:
    - Info: general_informations/info.md
    - URL + authentification: general_informations/URL_+_authentication.md
    - Elements: general_informations/elements.md
    - Changesets: general_informations/changesets.md
    - Tags: general_informations/tags.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/j%C4%99drzej-j-steckiewicz-395659334/

copyright: Copyright &copy; 2025 Jędrzej Steckiewicz